### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sbrunner** [sbrunner/admin-components#1]
## Examples

- [ ] One fetch
- [ ] Fetch every duration
- [ ] With refresh button
- [ ] With action link
- [ ] With form action

## Fetch element

 - [ ] Support reload on counter
 - [ ] Support reload every duration
 - [ ] Add dimension and nice spinner/error SVG icons

## Link element

- [ ] Create
- [ ] Do call, with spinner and error icons
- [ ] Increment a counter
- [ ] Set data
- [ ] Test with Bootstrap

## Form element(s) 

- [ ] Create
- [ ] Do call, with spinner and error icons
- [ ] Increment a counter
- [ ] Set data
- [ ] Test with Bootstrap

## Chore

- [ ] Setup Renovate
- [ ] Setup pre-commit
- [ ] Setup GHCI
- [ ] Setup test with image check
